[Verifiable Credentials 2019] Liaison with ISO SC17 WG10
w3c/charter-drafts pull request #246
Opened 2019-12-01 09:27 UTC by iherman

PR version of issue #245.

If merged, fix #245.

Cc @David-Chadwick

2019-12-01 09:32 UTC, iherman commented
Cc: @msporny @burnburn @stonematt

2019-12-01 09:55 UTC, David-Chadwick requested changes
I think it needs a CR/LF inserting to reduce the characters per line

2019-12-01 10:55 UTC, iherman commented
@David-Chadwick HTML will take care of that, see:

https://raw.githack.com/w3c/charter-drafts/VC19-ISO-SC17-liaison/verifiable-credentials-2019.html

B.t.w., does the WG have a Web site that could be linked to the text?

2019-12-01 16:37 UTC, msporny requested changes
Minor punctuation change, otherwise, LGTM.

2019-12-01 16:37 UTC, msporny commented on verifiable-credentials-2019.html
> +           <dd>Ensure that the mobile driving licenses being modeled and expressed by the ISO SC17 WG10 community are compatible with the work of the Verifiable Credentials WG</dd>
```suggestion
           <dd>Ensure that the mobile driving licenses being modeled and expressed by the ISO SC17 WG10 community are compatible with the work of the Verifiable Credentials WG.</dd>
```

2019-12-01 17:29 UTC, David-Chadwick commented
On 01/12/2019 10:55, Ivan Herman wrote:
>
> @David-Chadwick <https://github.com/David-Chadwick> HTML will take 
> care of that, see:
>
> https://raw.githack.com/w3c/charter-drafts/VC19-ISO-SC17-liaison/verifiable-credentials-2019.html
>
> B.t.w., does the WG have a Web site that could be linked to the text?
>
Not that I am aware of. It has pages for its deliverables and meeting 
minutes etc. Also I have created a Wikipedia page here 
[https://en.wikipedia.org/wiki/Verifiable_credentials].

Manu can give you the definitive answer about a WG web site.

Kind regards

David

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/w3c/charter-drafts/pull/246?email_source=notifications&email_token=AA33R72IXSCOELQM7CGTII3QWOJ33A5CNFSM4JTKX2A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFRFFVY#issuecomment-560091863>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AA33R7ZAVYT2R4Z7OHYSNZDQWOJ33ANCNFSM4JTKX2AQ>.
>

2019-12-01 17:55 UTC, msporny commented
@David-Chadwick wrote:
> Manu can give you the definitive answer about a WG web site.

@iherman is asking about the website for the ISO-SC17 group... which, I think, is technically  ISO/IEC JTC 1/SC 17/WG 10... which is listed here: https://www.iso.org/committee/45144.html

2019-12-01 17:57 UTC, iherman commented
Yes indeed! Thanks Manu, I will update the file on the repo tomorrow.

Ivan

---
Ivan Herman
World Wide Web Consortium
http://www.w3.org/People/Ivan/
ORCID: 0000-0003-0782-2704

On 1 Dec 2019, 18:55 +0100, Manu Sporny <notifications@github.com>, wrote:
> @David-Chadwick wrote:
> > Manu can give you the definitive answer about a WG web site.
> @iherman is asking about the website for the ISO-SC17 group... which, I think, is technically ISO/IEC JTC 1/SC 17/WG 10... which is listed here: https://www.iso.org/committee/45144.html
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-12-01 17:57 UTC, msporny requested changes
Add link to ISO SC17 WG10.

2019-12-01 17:57 UTC, msporny commented on verifiable-credentials-2019.html
> +           <dt>ISO SC17 WG10<dt>
```suggestion
           <dt><a href="https://www.iso.org/committee/45144.html">ISO/IEC JTC 1/SC 17/WG 10</a><dt>
```

2019-12-01 20:36 UTC, plehegar approved these changes

2019-12-02 08:11 UTC, iherman commented
Thanks @msporny I have committed both of your suggestions.

2019-12-02 10:46 UTC, plehegar approved these changes

2019-12-03 17:33 UTC, merged