Adds Digital Credentials from WICG
w3c/charter-drafts pull request #484
Opened 2024-03-04 16:03 UTC by plehegar

Following AC Review.

See also https://github.com/w3c/strategy/issues/427

cc @hlflanagan @asr-enid @timcappalli @wseltzer

2024-03-04 17:55 UTC, plehegar commented
(there is a separate question whether we should do an other AC review since this change is pretty significant)

2024-03-04 21:53 UTC, kdenhartog commented
My understanding was that the group hadn't reached consensus to leave this work in scope of the initial charter because this work is too new and still requires further discussion regarding privacy concerns and human rights concerns. I've expressed [this on the TPAC notes here](https://docs.google.com/document/d/12PLJQHrTCwFDcLeBvOiH3RjYHuVCF1a9ljYyPUj-S3o/edit) and in [the subsequent issue](https://github.com/fedidcg/fedidcg.github.io/issues/10) where this was noted here. It doesn't appear that Webkit or Mozilla expressed opinions contrary to this and were aware an issue was being made since they were present on the call where it was noted this would be the best place to discuss the topic. 

I don't believe we should add this at this time and an AC review should be necessary for the inclusion of this work. The use cases being addressed present a different privacy and security model in FedCM than in Digital Credentials API and should require broader review in my opinion.

2024-03-05 16:21 UTC, gffletch commented
If we keep the Digital Credentials addition, I'd recommend adding language that this working group will work with other industry standards efforts to protect against developing competing standards.

2024-03-05 16:46 UTC, plehegar commented
out of scope section will need to get revised as well. It currently lists "Interactions with identity wallets" as out of scope.

2024-03-07 21:02 UTC, hober approved these changes
Looks good to me!

2024-03-08 09:23 UTC, tlodderstedt requested changes

2024-03-08 09:23 UTC, tlodderstedt commented on 2024/wg-fedid.html
> +            mediate access to, and presentation of, digital credentials such as a driver's
I suggest to include issuance as well. Wallet based applications are incomplete without the issuance part. Furthermore, providing the web with an interoperable way for issuance will facilitate user's choice of their wallet.

2024-04-18 02:43 UTC, plehegar commented
Following conversations at IIW, folks came up with a new draft that includes the Digital Credentials API in the scope of the FedID Working Group:
  https://w3c.github.io/charter-drafts/2024/wg-fedid.html

Please, raise separate issues against the draft.

2024-04-18 02:43 UTC, closed without merging