[template] Adds a Tentative Deliverables section
w3c/charter-drafts pull request #502
Opened 2024-04-26 19:00 UTC by plehegar

This adds support in the charter template to list specifications that are being incubated but may get adopted later without rechartering.

2024-04-26 19:26 UTC, OR13 approved these changes

2024-04-26 21:21 UTC, tantek approved these changes
This looks like a reasonable placeholder to me. I'm curious what @cwilso thinks (per the AB's Incubation priority project).

2024-04-29 12:59 UTC, csarven reviewed
I think this section should briefly clarify/qualify what constitutes "incubation" with reference to existing W3C guide/recommendation. Along the lines of https://github.com/w3c/charter-drafts/issues/262#issuecomment-1858630873 , e.g.,:

>The Working Group will adopt proposals that fulfill the requirements of [W3C Recommendation Track Readiness](https://www.w3.org/Guide/standards-track/#criteria) [..] Proposals can be made to the Working Group through [W3C Community Groups](https://www.w3.org/groups/cg/) or another similar incubation phase.

It tries to ensure (or at least raises awareness about the common understanding) to some extent that incubation was achieved in a space that followed the principles of open standards development. This is to contrast "incubation" that may be done in private-space and to avoid potential rubber-stamping later on.

2024-04-29 18:02 UTC, hober approved these changes
This looks good to me. I like that it's pretty general, and doesn't presume that all incubations are done in WICG, or a W3C Community Group for that matter.

2024-04-29 20:10 UTC, cwilso requested changes

2024-04-29 20:10 UTC, cwilso commented on charter-template.html
> +            for the following documents:</p>
The phrasing "may produce Rec-track specification for the following documents" is odd; you don't produce a spec FOR a document.  I think there are two distinct cases - when you're adopting an already-known incubation, in which case I think it should say (with the incubation/interest/consensus caveats) "may adopt the following documents as Rec-track specifications."   You could also (additionally), if you're trying to leave space for where the incubation comes from, simply say "may produce Rec-track specifications in the following areas", and change the "draft state" to "possible adoption inputs" or something like that.

2024-05-01 21:16 UTC, tantek requested changes
agree with @cwilso's comments, and would like to see changes in this PR accordingly

2024-05-06 17:23 UTC, svgeesus approved these changes

2024-05-06 17:23 UTC, svgeesus commented on charter-template.html
> +            of the Group participants, the Working Group may also produce Recommendation-track specifications
```suggestion
            of the Group participants, the Working Group may adopt the following documents

2024-05-06 17:23 UTC, svgeesus commented on charter-template.html
> +            for the following documents:</p>
```suggestion
             as Rec-track specifications:</p>
```

2024-05-06 17:23 UTC, svgeesus commented on charter-template.html
> +            for the following documents:</p>
Added improved wording from cwilso

2024-05-06 17:25 UTC, merged