[wg/fedid] Update from PR to beyond CR
w3c/charter-drafts pull request #574
Opened 2024-08-23 08:47 UTC by simoneonofri

As per https://github.com/w3c/charter-drafts/issues/566 by @frivoal

[cc @wseltzer @hlflanagan]

2024-08-26 03:10 UTC, frivoal commented on 2024/wg-fedid.html
>          to
```suggestion
```
I don't think this word is necessary after the other changes

2024-08-27 07:15 UTC, frivoal approved these changes
Thanks. I think this is a useful change, and suggest adopting it in the charter template as well.

2024-09-11 00:36 UTC, tantek requested changes
Looks good except suggest same change that @jyasskin suggested in #578, no need to duplicate element content in title attribute.

2024-09-11 00:36 UTC, tantek commented on 2024/wg-fedid.html
> +        <i>beyond</i> <a href="https://www.w3.org/policies/process/#RecsCR" title="Candidate Recommendation">Candidate Recommendation</a>, each normative specification is expected to have
```suggestion
        <i>beyond</i> <a href="https://www.w3.org/policies/process/#RecsCR">Candidate Recommendation</a>, each normative specification is expected to have
```

2024-09-20 17:33 UTC, tantek approved these changes

2024-10-03 12:51 UTC, merged