Accurately quote the W3C's mission.
w3c/charter-drafts pull request #609
Opened 2024-10-16 17:29 UTC by jyasskin

And make the quotation marks copyable.

2024-10-19 02:32 UTC, tantek requested changes
The W3C Mission is still in-progress and I disagree with an attempt to precisely quote it in a charter (which will get frozen once approved). 

Instead, mention something higher level, and replace that whole paragraph with something shorter like:

> W3C's Mission(linked) includes privacy and security for the web.

Then simplify the next sentence (in the next paragraph) like this:

s/The last two requirements, Privacy and Security, are integral to/Both of these are integral to/

Then collapse those two paragraphs into one to simplify and shorten the charter.

2024-10-19 02:33 UTC, tantek commented on 2024/ig-security.html
> +        <p>W3C’s <a href="https://www.w3.org/mission/">mission</a> is to “develop open standards for an interoperable web to meet requirements for accessibility, internationalization, privacy, and se
```suggestion
        <p>W3C’s <a href="https://www.w3.org/mission/">mission</a> includes privacy and security for the web.
```

2024-10-19 02:34 UTC, tantek commented on 2024/ig-security.html
>          <p>The last two requirements, Privacy and Security, are integral to <a href="https://www.un.org/en/about-us/universal-declaration-of-human-rights" title="Article 3: Everyone has the right to
```suggestion
        Both of these are integral to <a href="https://www.un.org/en/about-us/universal-declaration-of-human-rights" title="Article 3: Everyone has the right to life, liberty and security of person.">human rights</a> and <a href="https://www.ohchr.org/en/instruments-mechanisms/instruments/international-covenant-civil-and-political-rights" title="Article 9: Everyone has the right to liberty and security of person">civil liberties</a> and have always been of the Consortium's concern.</p>
```

2024-10-19 02:38 UTC, jyasskin commented
@tantek's change is fine with me. The mission was quoted at all because of @mnot's comment in the [previous review](https://www.w3.org/2002/09/wbs/33280/sing/results), so he should get a chance to weigh in.

2024-10-19 02:50 UTC, mnot commented
I was only concerned with it being misquoted / mischaracterised.

2024-10-19 03:31 UTC, tantek commented
@mnot wrote:
> I was only concerned with it being misquoted / mischaracterised.

Do my proposed changes (in https://github.com/w3c/charter-drafts/pull/609#pullrequestreview-2379185442 and subsequent suggested changes) address those concerns and/or can you live with my proposed changes?

2024-10-19 12:00 UTC, simoneonofri approved these changes

2024-10-20 22:25 UTC, mnot commented
They're not saying what the mission **is**, so I think you avoid the original issue.

2024-10-21 17:40 UTC, tantek commented
@jyasskin wrote:
> @tantek's change is fine with me.

Thanks. If you can accept my changes into this PR I'll re-review and approve.

2024-10-21 18:37 UTC, simoneonofri commented
@jyasskin, @tantek, and @mnot, thank you for the useful discussion. The thinking here, too, might be important for making charters more resilient to various changes.

@jyasskin I was thinking about the usage of `<q>` vs. the normal one with `"`
I am waiting for the acceptance and review to Merge and close.

2024-10-21 20:11 UTC, jyasskin commented
I've merged @tantek's suggested changes, and retitled the PR to match.

2024-10-21 20:37 UTC, tantek approved these changes

2024-10-24 08:17 UTC, merged